/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cyberpunk_characterglb.glb --transform 
Files: cyberpunk_characterglb.glb [78.58MB] > C:\Users\antoi\Documents\fringuant-technical-test\public\models\cyberpunk_characterglb-transformed.glb [1.52MB] (98%)
Author: 4d_Bob (https://sketchfab.com/3d_Bob)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-character-019f4b3fd3c74ed0bc6c8dbe9cd50d51
Title: Cyberpunk character
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Character(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../../public/models/cyberpunk_characterglb-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_68"
          geometry={nodes.Object_68.geometry}
          material={materials.material}
          skeleton={nodes.Object_68.skeleton}
          rotation={[-Math.PI / 2, Math.PI, -Math.PI]}
          scale={0.017}
        />
        <skinnedMesh
          name="Object_70"
          geometry={nodes.Object_70.geometry}
          material={materials.material_3}
          skeleton={nodes.Object_70.skeleton}
          rotation={[-Math.PI / 2, Math.PI, -Math.PI]}
          scale={0.017}
        />
        <skinnedMesh
          name="Object_72"
          geometry={nodes.Object_72.geometry}
          material={materials.material_3}
          skeleton={nodes.Object_72.skeleton}
          rotation={[-Math.PI / 2, Math.PI, -Math.PI]}
          scale={0.017}
        />
        <skinnedMesh
          name="Object_74"
          geometry={nodes.Object_74.geometry}
          material={materials.material}
          skeleton={nodes.Object_74.skeleton}
          rotation={[-Math.PI / 2, Math.PI, -Math.PI]}
          scale={0.017}
        />
        <skinnedMesh
          name="Object_76"
          geometry={nodes.Object_76.geometry}
          material={materials.material}
          skeleton={nodes.Object_76.skeleton}
          rotation={[-Math.PI / 2, Math.PI, -Math.PI]}
          scale={0.017}
        />
        <skinnedMesh
          name="Object_78"
          geometry={nodes.Object_78.geometry}
          material={materials.material_3}
          skeleton={nodes.Object_78.skeleton}
          rotation={[-Math.PI / 2, Math.PI, -Math.PI]}
          scale={0.017}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cyberpunk_characterglb-transformed.glb");
